# Getting Started with the Data Science Service

Data Science service uses [conda](https://anaconda.org/) environments to manage python dependencies.

[![Notebook Examples](https://img.shields.io/badge/docs-notebook--examples-blue)](https://github.com/oracle-samples/oci-data-science-ai-samples/tree/master/notebook_examples)
[![Conda Environments](https://img.shields.io/badge/docs-conda--environments-blue)](https://docs.oracle.com/en-us/iaas/data-science/using/conda_understand_environments.htm)
[![Source Code](https://img.shields.io/badge/source-accelerated--datascience-blue)](https://github.com/oracle/accelerated-data-science)

## Upgrade Accelerated Data Science SDK - `oracle-ads`

The Oracle Accelerated Data Science (ADS) SDK is maintained by the Oracle Cloud Infrastructure Data Science service team. It speeds up common data science activities by providing tools that automate and/or simplify common data science tasks, along with providing a data scientist friendly pythonic interface to Oracle Cloud Infrastructure (OCI) services, most notably OCI Data Science, Data Flow, Object Storage, and the Autonomous Database. ADS gives you an interface to manage the lifecycle of machine learning models, from data acquisition to model evaluation, interpretation, and model deployment.

Before you begin with a conda environment, upgrade `oracle-ads` library - [![PyPI](https://img.shields.io/pypi/v/oracle-ads.svg)](https://pypi.org/project/oracle-ads/)  [![Python](https://img.shields.io/pypi/pyversions/oracle-ads.svg?style=plastic)](https://pypi.org/project/oracle-ads/)


You can check your version of `oracle-ads` by running -

In [8]:
import ads

print(ads.__version__)

2.13.5

In [9]:
# Uncomment this code and set the correct proxy links if have to setup proxy for internet
# import os
# os.environ['http_proxy']="http://myproxy"
# os.environ['https_proxy']="http://myproxy"

# Use os.environ['no_proxy'] to route trafic directly

In [10]:
# To upgrade run -
#! pip install oracle-ads --upgrade
! pip install geopandas
#!pip install --upgrade oci
#!pip install --upgrade ads

Requirement already satisfied: geopandas in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (1.1.1)
Requirement already satisfied: numpy>=1.24 in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (from geopandas) (1.26.4)
Requirement already satisfied: pyogrio>=0.7.2 in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (from geopandas) (0.11.1)
Requirement already satisfied: packaging in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (from geopandas) (24.2)
Requirement already satisfied: pandas>=2.0.0 in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (from geopandas) (2.2.2)
Requirement already satisfied: pyproj>=3.5.0 in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (from geopandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: certifi in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (from pyogrio>=0.7.2->geopandas) (2025.1.31)
Requirement already satisfied: six>=1.5 in ./conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

## Authentication
To interact with oci services you need to authenticate with one of the following mechanism -

### 1. Resource Principal

Resource Principal works by authorizing the notebook instance that you are using to read/manage OCI service resource such as Object Storage, Data Science Jobs, Data Science Models, Data Science Model Deployment, etc. Check these references - 
    
- Refer how to setup policy for managing Data science service resource [here](https://docs.oracle.com/en-us/iaas/data-science/using/policies.htm)
- Refer how to setup policy for managing Object Storage service resource [here](https://docs.oracle.com/en-us/iaas/Content/Identity/policiescommon/commonpolicies.htm#write-objects-to-buckets)
    
    
Other useful resources - 

- https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/commonpolicies.htm
- https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/policygetstarted.htm#Getting_Started_with_Policies

Once the policies are setup, configure `oracle-ads` to use resource principal as follows - 


```python
ads.set_auth('resource_principal')
```

### 2. API Key

To setup API Key refer - 

- https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm
- https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm


Once you have setup the config and the keys, you can setup ads to use API Keys - 

```python

ads.set_auth('api_key')

```

## Working with Data on Object Storage

In [11]:
import ads
import pandas as pd

ads.set_auth("resource_principal")

In [12]:
bucket_name = "risk_admission_bucket"
namespace = "idi1o0a010nx"


file_name = "dataset_ed_admission.csv"
df = pd.read_csv(
    f"oci://{bucket_name}@{namespace}/{file_name}",
    storage_options=ads.common.auth.default_signer(),
)

In [13]:
df.head()

,subject_id,hadm_id,stay_id,intime,outtime,gender,race,arrival_transport,disposition,admitted_from_ed,temperature,heartrate,resprate,o2sat,sbp,dbp,n_diagnosis,split
0,10014729,23300884.0,37887480,2125-03-19 12:36:00,2125-03-19 16:59:47,F,WHITE - OTHER EUROPEAN,WALK IN,ADMITTED,1,99.1,90.0,26.0,NaN,86.0,61.0,4.0,train
1,10018328,26706939.0,34176810,2154-02-05 17:09:00,2154-02-05 22:54:00,F,WHITE,AMBULANCE,ADMITTED,1,97.7,74.0,20.0,96.0,133.0,65.0,1.0,val
2,10018328,NaN,32103106,2154-08-03 15:31:00,2154-08-03 22:29:00,F,WHITE,AMBULANCE,HOME,0,96.2,74.0,18.0,100.0,142.0,75.0,1.0,val
3,10020640,27984218.0,38797992,2153-02-12 21:59:00,2153-02-13 01:38:00,F,WHITE,AMBULANCE,ADMITTED,1,99.2,130.0,32.0,94.0,106.0,74.0,5.0,val
4,10015272,27993466.0,33473053,2137-06-12 16:54:00,2137-06-12 18:37:22,F,WHITE,AMBULANCE,ADMITTED,1,97.5,118.0,18.0,96.0,100.0,56.0,1.0,train

### Working with other sources

Learn how to work with other sources [here](https://accelerated-data-science.readthedocs.io/en/latest/user_guide/loading_data/connect.html)

## References

* [Oracle Accelerated Data Science SDK Guide](https://accelerated-data-science.readthedocs.io/en/latest/)
* [Oracle Accelerated Data Science Source Code](https://github.com/oracle/accelerated-data-science)
* [Notebook Examples](https://github.com/oracle-samples/oci-data-science-ai-samples/tree/master/notebook_examples)
* [Conda environments](https://docs.oracle.com/en-us/iaas/data-science/using/conda_understand_environments.htm)
* [Publish Conda Environments](https://docs.oracle.com/en-us/iaas/data-science/using/conda_publishs_object.htm)

In [14]:
## Download Wallet

import os, io, zipfile, requests
from urllib.parse import urlparse, parse_qs, urlencode, urlunparse

def normalize_dropbox_url(u: str) -> str:
    """
    - Se for www.dropbox.com, força dl=1 (download direto)
    - Também funciona para links de pasta (/scl/fo/...) e de arquivo (/s/...)
    - Alternativa: trocar host para dl.dropboxusercontent.com
    """
    p = urlparse(u)
    q = parse_qs(p.query)
    q["dl"] = ["1"]  # força download
    new_query = urlencode({k: v[0] for k, v in q.items()})
    return urlunparse((p.scheme, p.netloc, p.path, p.params, new_query, p.fragment))

def download_dropbox_zip(url, out_path, chunk=1<<20):
    url = normalize_dropbox_url(url)
    with requests.get(url, stream=True, allow_redirects=True, timeout=120) as r:
        r.raise_for_status()
        # cheque simples de conteúdo
        ctype = r.headers.get("content-type","").lower()
        # Dropbox às vezes serve "application/zip" ou "application/binary"
        if "text/html" in ctype:
            raise RuntimeError("O Dropbox devolveu HTML (provável link sem dl=1 ou sem permissão).")
        with open(out_path, "wb") as f:
            for part in r.iter_content(chunk_size=chunk):
                if part:
                    f.write(part)
    # valida o ZIP
    if not zipfile.is_zipfile(out_path):
        raise RuntimeError(f"Arquivo salvo não é um ZIP válido: {out_path}")
    # teste de integridade
    with zipfile.ZipFile(out_path) as z:
        bad = z.testzip()
        if bad:
            raise RuntimeError(f"ZIP corrompido. Primeiro arquivo com problema: {bad}")
    return out_path

# ---- use aqui o SEU link de compartilhamento (de pasta ou arquivo) ----
url = "https://<link para baixar o Wallet se houver>"
zip_path = "Wallet_ORADB23ai.zip"

download_dropbox_zip(url, zip_path)
print("ZIP baixado e validado:", zip_path)

ZIP baixado e validado: Wallet_ORADB23ai.zip

In [ ]:
## Working with Autonomous Database

# If you are using Wallet file, provide the zip file path for `wallet_location`
connection_parameters = {
    "user_name": "admin",
    "password": "********",
    "service_name": "oradb23ai_high",
    "wallet_location": "Wallet.zip",
}
import pandas as pd
import ads

# read of a SQL query into a dataframe with a bind variable. Use bind variables
# rather than string substitution to avoid the SQL injection attack vector.
df = pd.DataFrame.ads.read_sql(
    """
    select * from ADMIN.DATASET_ED_ADMISSION
    WHERE
        SPLIT <= :split
    """,
    bind_variables={
        "split" : "train"
    }
    ,
    connection_parameters=connection_parameters,
)

print(df)

train = df

     SUBJECT_ID     HADM_ID   STAY_ID              INTIME             OUTTIME  \
0      10014729  23300884.0  37887480 2125-03-19 12:36:00 2125-03-19 16:59:47
1      10015272  27993466.0  33473053 2137-06-12 16:54:00 2137-06-12 18:37:22
2      10016810  20973395.0  35758326 2185-06-15 23:08:00 2185-06-16 02:16:00
3      10016810         NaN  31824062 2185-07-08 11:55:00 2185-07-08 11:59:00
4      10006580         NaN  32259573 2137-09-29 21:06:00 2137-09-29 22:54:00
..          ...         ...       ...                 ...                 ...
198    10017492  27417763.0  38213541 2116-06-26 14:29:00 2116-06-26 18:26:30
199    10038999  29026789.0  34205403 2132-05-17 19:56:00 2132-05-18 01:36:00
200    10038999  27189241.0  30272878 2131-05-22 20:33:00 2131-05-22 21:50:33
201    10009049  22995465.0  31628990 2174-05-26 04:20:00 2174-05-26 09:18:00
202    10004457  28723315.0  32405286 2141-08-12 12:08:00 2141-08-12 17:20:00

    GENDER                          RACE ARRIVAL_TRANSPORT DISPOSITION  \
0        F        WHITE - OTHER EUROPEAN           WALK IN    ADMITTED
1        F                         WHITE         AMBULANCE    ADMITTED
2        F                       UNKNOWN           UNKNOWN    ADMITTED
3        F                       UNKNOWN           UNKNOWN       OTHER
4        F  HISPANIC/LATINO - SALVADORAN           WALK IN        HOME
..     ...                           ...               ...         ...
198      M    PATIENT DECLINED TO ANSWER         AMBULANCE    ADMITTED
199      M                         WHITE         AMBULANCE    ADMITTED
200      M                         WHITE           UNKNOWN    ADMITTED
201      M                         WHITE         AMBULANCE    ADMITTED
202      M                         WHITE           WALK IN    ADMITTED

     ADMITTED_FROM_ED  TEMPERATURE  HEARTRATE  RESPRATE  O2SAT    SBP   DBP  \
0                   1         99.1       90.0      26.0    NaN   86.0  61.0
1                   1         97.5      118.0      18.0   96.0  100.0  56.0
2                   1         98.8       72.0      18.0   90.0   98.0  48.0
3                   0          NaN        NaN       NaN    NaN    NaN   NaN
4                   0         98.1       89.0      18.0   96.0  131.0  90.0
..                ...          ...        ...       ...    ...    ...   ...
198                 1          NaN        NaN       NaN    NaN    NaN   NaN
199                 1         97.6      116.0      14.0   99.0  140.0  78.0
200                 1          NaN        NaN       NaN    NaN    NaN   NaN
201                 1         99.0       87.0      18.0   96.0  126.0  68.0
202                 1         97.6      103.0      16.0   98.0  138.0  72.0

     N_DIAGNOSIS  SPLIT
0              4  train
1              1  train
2              1  train
3              1  train
4              1  train
..           ...    ...
198            2  train
199            2  train
200            1  train
201            1  train
202            4  train

[203 rows x 18 columns]

In [16]:
## Visualize Data

TARGET_COL = "admitted_from_ed"  # ajuste se houver alvo; se não houver, pode deixar None

import pandas as pd, numpy as np, ads, sys

print("oracle-ads version:", getattr(ads, "__version__", "unknown"))

# --- 0) Higieniza tipos para evitar falhas no type_discovery ---
df_clean = df.copy()
# datas (heurística por nome de coluna)
for c in df_clean.columns:
    cl = c.lower()
    if any(k in cl for k in ["time", "date", "_at", "dt"]):
        try:
            df_clean[c] = pd.to_datetime(df_clean[c], errors="coerce")
        except Exception:
            pass
# categorias leves
for c in df_clean.select_dtypes(include=["object"]).columns:
    if 1 < df_clean[c].nunique(dropna=True) <= 1000:
        df_clean[c] = df_clean[c].astype("category")

DATASET_NAME = "ED Admission"
DATASET_DESC = "Dataset PS para modelagem"

ds = None
last_err = None

# --- 1) Tentativa principal: DatasetFactory ---
try:
    from ads.dataset.factory import DatasetFactory
    try:
        ds = DatasetFactory.from_dataframe(
            df_clean,
            target=TARGET_COL,
            dataset_name=DATASET_NAME,
            dataset_description=DATASET_DESC,
            type_discovery=False  # evita o erro de typed discovery
        )
        print("✔ Usando DatasetFactory (type_discovery=False)")
    except TypeError:
        ds = DatasetFactory.from_dataframe(
            df_clean,
            target=TARGET_COL,
            dataset_name=DATASET_NAME,
            dataset_description=DATASET_DESC
        )
        print("✔ Usando DatasetFactory (sem type_discovery)")
except Exception as e:
    last_err = e

# --- 2) Fallback: construtor direto ADSDataset ---
if ds is None:
    try:
        from ads.dataset.dataset import ADSDataset
        try:
            ds = ADSDataset(
                df_clean,
                target=TARGET_COL,
                name=DATASET_NAME,
                description=DATASET_DESC,
                type_discovery=False
            )
            print("✔ Usando ADSDataset(...) (type_discovery=False)")
        except TypeError:
            ds = ADSDataset(
                df_clean,
                target=TARGET_COL,
                name=DATASET_NAME,
                description=DATASET_DESC
            )
            print("✔ Usando ADSDataset(...) (sem type_discovery)")
    except Exception as e2:
        last_err = e2

# --- 3) Fallback: construtor direto Dataset (nome antigo) ---
if ds is None:
    try:
        from ads.dataset.dataset import Dataset
        try:
            ds = Dataset(
                df_clean,
                target=TARGET_COL,
                name=DATASET_NAME,
                description=DATASET_DESC,
                type_discovery=False
            )
            print("✔ Usando Dataset(...) (type_discovery=False)")
        except TypeError:
            ds = Dataset(
                df_clean,
                target=TARGET_COL,
                name=DATASET_NAME,
                description=DATASET_DESC
            )
            print("✔ Usando Dataset(...) (sem type_discovery)")
    except Exception as e3:
        last_err = e3

# --- 4) Fallback (mais raro): DataFrameDataset ---
if ds is None:
    try:
        from ads.dataset.dataframe_dataset import DataFrameDataset
        ds = DataFrameDataset(
            df_clean,
            target=TARGET_COL,
            name=DATASET_NAME,
            description=DATASET_DESC
        )
        print("✔ Usando DataFrameDataset(...)")
    except Exception as e4:
        last_err = e4

# --- Finalização: roles + visualização ---
if ds is not None:
    # if "stay_id" in df_clean.columns:
    #     ds.set_role("stay_id", "id")
    # for col in ["intime","outtime","first_vitals_time","first_pyxis_time"]:
    #     if col in df_clean.columns:
    #         ds.set_role(col, "timestamp")
    
    from bokeh.io import reset_output, output_notebook
    reset_output()
    ds.show_in_notebook()
else:
    # Último recurso: visão rápida do DF caso nenhuma classe esteja disponível
    print("✖ Não consegui construir o objeto Dataset do ADS.")
    print("Último erro capturado:", last_err)
    from IPython.display import display
    display(df_clean.head())
    print(df_clean.info())

oracle-ads version: 2.13.5

loop1:   0%|          | 0/4 [00:00<?, ?it/s]

✖ Não consegui construir o objeto Dataset do ADS.
Último erro capturado: No module named 'ads.dataset.dataframe_dataset'

,SUBJECT_ID,HADM_ID,STAY_ID,INTIME,OUTTIME,GENDER,RACE,ARRIVAL_TRANSPORT,DISPOSITION,ADMITTED_FROM_ED,TEMPERATURE,HEARTRATE,RESPRATE,O2SAT,SBP,DBP,N_DIAGNOSIS,SPLIT
0,10014729,23300884.0,37887480,2125-03-19 12:36:00,2125-03-19 16:59:47,F,WHITE - OTHER EUROPEAN,WALK IN,ADMITTED,1,99.1,90.0,26.0,NaN,86.0,61.0,4,train
1,10015272,27993466.0,33473053,2137-06-12 16:54:00,2137-06-12 18:37:22,F,WHITE,AMBULANCE,ADMITTED,1,97.5,118.0,18.0,96.0,100.0,56.0,1,train
2,10016810,20973395.0,35758326,2185-06-15 23:08:00,2185-06-16 02:16:00,F,UNKNOWN,UNKNOWN,ADMITTED,1,98.8,72.0,18.0,90.0,98.0,48.0,1,train
3,10016810,NaN,31824062,2185-07-08 11:55:00,2185-07-08 11:59:00,F,UNKNOWN,UNKNOWN,OTHER,0,NaN,NaN,NaN,NaN,NaN,NaN,1,train
4,10006580,NaN,32259573,2137-09-29 21:06:00,2137-09-29 22:54:00,F,HISPANIC/LATINO - SALVADORAN,WALK IN,HOME,0,98.1,89.0,18.0,96.0,131.0,90.0,1,train

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SUBJECT_ID         203 non-null    int64
 1   HADM_ID            158 non-null    float64
 2   STAY_ID            203 non-null    int64
 3   INTIME             203 non-null    datetime64[ns]
 4   OUTTIME            203 non-null    datetime64[ns]
 5   GENDER             203 non-null    category
 6   RACE               203 non-null    category
 7   ARRIVAL_TRANSPORT  203 non-null    category
 8   DISPOSITION        203 non-null    category
 9   ADMITTED_FROM_ED   203 non-null    int64
 10  TEMPERATURE        179 non-null    float64
 11  HEARTRATE          181 non-null    float64
 12  RESPRATE           182 non-null    float64
 13  O2SAT              181 non-null    float64
 14  SBP                182 non-null    float64
 15  DBP                182 non-null    float64
 16  N_DIAGNOSIS        203 non-null    int64
 17  SPLIT              203 non-null    category
dtypes: category(5), datetime64[ns](2), float64(7), int64(4)
memory usage: 22.9 KB
None

In [25]:
## Verifica a versão do sklearn e se está executando via o package correto

import sklearn, sys
print("treino sklearn:", sklearn.__version__)
print(sys.version)

import ads
print("treino ads:", ads.__version__)

treino sklearn: 1.3.2
3.11.11 | packaged by conda-forge | (main, Mar  3 2025, 20:43:55) [GCC 13.3.0]
treino ads: 2.13.5

In [18]:
## Train with scikit-learning (Produção)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, cohen_kappa_score

# ----------------------------------
# 1) Normaliza nomes de colunas
# ----------------------------------
def normalize_cols(df: pd.DataFrame) -> pd.DataFrame:
    cols = (
        df.columns.astype(str)
          .str.strip()
          .str.replace(r"\s+", "_", regex=True)
          .str.replace(r"[^\w]+", "_", regex=True)
          .str.replace(r"_+", "_", regex=True)
          .str.strip("_")
          .str.lower()
    )
    df2 = df.copy()
    df2.columns = cols
    return df2

dfn = normalize_cols(df)

# ----------------------------------
# 2) Define target (já 0/1)
# ----------------------------------
TARGET_COL = "admitted_from_ed"
if TARGET_COL not in dfn.columns:
    raise KeyError(f"Coluna {TARGET_COL} não encontrada no DataFrame!")

dfn[TARGET_COL] = dfn[TARGET_COL].astype(int)

# ----------------------------------
# 3) Features
# ----------------------------------
# gera features extras a partir das datas
for c in ["intime", "outtime"]:
    if c in dfn.columns:
        dfn[c] = pd.to_datetime(dfn[c], errors="coerce")

if {"intime","outtime"} <= set(dfn.columns):
    dfn["los_minutes"] = (dfn["outtime"] - dfn["intime"]).dt.total_seconds()/60
    dfn["arrival_hour"] = dfn["intime"].dt.hour
    dfn["arrival_weekday"] = dfn["intime"].dt.day_name()

candidate_features = [
    "gender","race","arrival_transport",
    "temperature","heartrate","resprate","o2sat","sbp","dbp",
    "n_diagnosis","los_minutes","arrival_hour","arrival_weekday"
]
features = [c for c in candidate_features if c in dfn.columns]

X = dfn[features].copy()
y = dfn[TARGET_COL]

# ----------------------------------
# 4) Split train/test
# ----------------------------------
if "split" in dfn.columns:
    train_mask = dfn["split"].astype(str).str.lower().eq("train")
    val_mask   = dfn["split"].astype(str).str.lower().isin(["val","test"])
    X_train, y_train = X[train_mask], y[train_mask]
    X_test, y_test   = X[val_mask], y[val_mask]
else:
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

# ----------------------------------
# 5) Pipeline com RandomForest
# ----------------------------------
cat_cols = X_train.select_dtypes(include=["object","category"]).columns.tolist()
num_cols = [c for c in features if c not in cat_cols]

pre = ColumnTransformer(
    transformers=[
        ("cat", Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("onehot",  OneHotEncoder(handle_unknown="ignore"))
        ]), cat_cols),
        ("num", Pipeline(steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler",  StandardScaler())
        ]), num_cols),
    ]
)

clf = Pipeline(steps=[
    ("preprocess", pre),
    ("model", RandomForestClassifier(
        class_weight="balanced",
        n_estimators=300,
        random_state=42
    ))
])

# ----------------------------------
# 6) Treino e avaliação
# ----------------------------------
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred, digits=3))
print("Kappa:", cohen_kappa_score(y_test, y_pred))
print("Matriz de confusão:\n", confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0      0.333     0.143     0.200         7
           1      0.867     0.951     0.907        41

    accuracy                          0.833        48
   macro avg      0.600     0.547     0.553        48
weighted avg      0.789     0.833     0.804        48

Kappa: 0.12328767123287676
Matriz de confusão:
 [[ 1  6]
 [ 2 39]]

In [19]:
## Salvar o modelo scikit-learning

import joblib, os
os.makedirs("artifacts", exist_ok=True)
joblib.dump(clf, "artifacts/model.pkl")          # seu Pipeline scikit-learn
joblib.dump(list(X_train.columns), "artifacts/feature_order.pkl")  # ordem das colunas
print("backup local OK")

backup local OK

In [20]:
## Registrar no Model Catalog

import ads
ads.set_auth(
    auth="api_key",
    oci_config_location="/home/datascience/.oci/config",
    profile="DEFAULT"
)

import os, joblib
from ads.model.framework.sklearn_model import SklearnModel

compartment_id = "ocid1.compartment.oc1..aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
#conda_slug     = "oci://service-conda-packs@id19sfcrra6z/service_pack/cpu/Oracle_AutoMLx_v25.1_for_CPU_on_Python_3.11/2.0/automlx251_p311_cpu_x86_64_v2"   # igual ao exemplo oficial
conda_slug = "automlx251_p311_cpu_x86_64_v2"
project_id = "ocid1.datascienceproject.oc1.sa-saopaulo-1.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

# (opcional) salvar artefatos locais
# os.makedirs("artifacts", exist_ok=True)
# joblib.dump(clf, "artifacts/model.pkl")

artifact_dir = "oci_model_artifact"  # diretório de trabalho local do pacote
sk = SklearnModel(estimator=clf, artifact_dir=artifact_dir, X_sample=X_train.head(5))

sk.prepare(
    training_conda_env=conda_slug,
    inference_conda_env=conda_slug,      # OU: inference_conda_env_path="oci://<bucket@ns>/.../conda_pack.tar.gz"
    X_sample=X_train.head(5),  # …mas **garanta aqui** no prepare também
    force_overwrite=True,
    model_input_serializer="cloudpickle"  # remove o warning futuro
)

# **REGISTRA** no Model Catalog
sk.save(
    display_name="ED-Admission RF",
    description="RandomForest admitted_from_ed (0/1)",
    compartment_id=compartment_id,
)

model_id = getattr(sk, "model_id", None) or getattr(getattr(sk, "dsc_model", None), "id", None)
print("Model ID:", model_id)

# 🔹 DEPLOY do modelo (cria endpoint REST ativo)
deployment = sk.deploy(
    display_name="ED-Admission Deployment",
    compartment_id=compartment_id,
    project_id=project_id,
    deployment_instance_shape="VM.Standard.E3.Flex",
    instance_count=1
)

print("Deployment OCID:", deployment.id)
print("Deployment endpoint:", deployment.url)

# 🔹 Teste de predição local
print("Local predict:", sk.predict(X_train.head(3)))

WARNING:ads.common:In the future model input will be serialized by `cloudpickle` by default. Currently, model input are serialized into a dictionary containing serialized input data and original data type information.Set `model_input_serializer="cloudpickle"` to use cloudpickle model input serializer.
WARNING:py.warnings:/home/datascience/conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages/ads/model/runtime/env_info.py:92: UserWarning: slug will be deprecated. Provide conda pack path instead.             ?, ?it/s]
  warnings.warn("slug will be deprecated. Provide conda pack path instead.")

Start loading model.joblib from model directory /home/datascience/oci_model_artifact ...
Model is successfully loaded.
['input_schema.json', 'score.py', '.model-ignore', 'runtime.yaml', 'test_json_output.json', 'model.joblib']

loop1:   0%|          | 0/4 [00:00<?, ?it/s]

WARNING:ads.model.datascience_model:the JSON object must be str, bytes or bytearray, not Schema
Model ID: ocid1.datasciencemodel.oc1.sa-saopaulo-1.amaaaaaafioir7iaq5rnhagfiztsbom7bzqvyenwrcsta3g67qvfllf5erna
Model Deployment OCID: ocid1.datasciencemodeldeployment.oc1.sa-saopaulo-1.amaaaaaafioir7iafffqtvgm2mj24zw7vnnyamcxzhwqelkdpg5n5qw4jgkq

Creating model deployment:   0%|          | [00:00<?, ?it/s]

Deployment OCID: ocid1.datasciencemodeldeployment.oc1.sa-saopaulo-1.amaaaaaafioir7iafffqtvgm2mj24zw7vnnyamcxzhwqelkdpg5n5qw4jgkq
Deployment endpoint: https://modeldeployment.sa-saopaulo-1.oci.customer-oci.com/ocid1.datasciencemodeldeployment.oc1.sa-saopaulo-1.amaaaaaafioir7iafffqtvgm2mj24zw7vnnyamcxzhwqelkdpg5n5qw4jgkq
Local predict: {'code': 'NotAuthorizedOrNotFound', 'message': 'Authorization failed or requested resource not found.'}

In [21]:
## Validate

MODEL_FILE = os.path.join(artifact_dir, "model.joblib")

def load_model(model_path=MODEL_FILE):
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Modelo não encontrado em: {model_path}")
    return joblib.load(model_path)

def predict(data, model=None) -> dict:
    # carrega sob demanda (não avalia nada no momento do import)
    if model is None:
        model = load_model()

    if isinstance(data, str):
        X = pd.read_json(io.StringIO(data))
    elif isinstance(data, dict):
        X = pd.DataFrame.from_dict(data)
    else:
        # já é DataFrame/array?
        X = pd.DataFrame(data)

    preds = model.predict(X).tolist()
    return {"prediction": preds}

payload = X_train.iloc[:5].to_json(orient="records")

print(payload)

import sys
sys.path.insert(0, artifact_dir)

from score import load_model, predict  # do pacote gerado

_ = load_model()                       # carrega o model.joblib
preds = predict(payload, _)            # chama a função predict do score.py
print(preds)

[{"gender":"F","race":"WHITE - OTHER EUROPEAN","arrival_transport":"WALK IN","temperature":99.1,"heartrate":90.0,"resprate":26.0,"o2sat":null,"sbp":86.0,"dbp":61.0,"n_diagnosis":4,"los_minutes":263.7833333333,"arrival_hour":12,"arrival_weekday":"Monday"},{"gender":"F","race":"WHITE","arrival_transport":"AMBULANCE","temperature":97.5,"heartrate":118.0,"resprate":18.0,"o2sat":96.0,"sbp":100.0,"dbp":56.0,"n_diagnosis":1,"los_minutes":103.3666666667,"arrival_hour":16,"arrival_weekday":"Wednesday"},{"gender":"F","race":"UNKNOWN","arrival_transport":"UNKNOWN","temperature":98.8,"heartrate":72.0,"resprate":18.0,"o2sat":90.0,"sbp":98.0,"dbp":48.0,"n_diagnosis":1,"los_minutes":188.0,"arrival_hour":23,"arrival_weekday":"Wednesday"},{"gender":"F","race":"UNKNOWN","arrival_transport":"UNKNOWN","temperature":null,"heartrate":null,"resprate":null,"o2sat":null,"sbp":null,"dbp":null,"n_diagnosis":1,"los_minutes":4.0,"arrival_hour":11,"arrival_weekday":"Friday"},{"gender":"F","race":"HISPANIC\/LATINO - SALVADORAN","arrival_transport":"WALK IN","temperature":98.1,"heartrate":89.0,"resprate":18.0,"o2sat":96.0,"sbp":131.0,"dbp":90.0,"n_diagnosis":1,"los_minutes":108.0,"arrival_hour":21,"arrival_weekday":"Sunday"}]
Start loading model.joblib from model directory /home/datascience/oci_model_artifact ...
Model is successfully loaded.
WARNING:py.warnings:/home/datascience/oci_model_artifact/score.py:100: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_json(json_data, dtype=fetch_data_type_from_schema(input_schema_path))

{'prediction': [1, 1, 1, 0, 0]}

In [26]:
## Consumindo o Endpoint - Código Simples

import requests
import oci
import pandas as pd
from ads.model.deployment import ModelDeployment
import os
from oci.signer import Signer
import ads

# Profile do OCI-CLI
PROFILE = "DEFAULT"

# Em caso de estar no notebook integrado ao processo de deployment do modelo - habilitar
print("Deployment OCID:", deployment.id)
print("Deployment endpoint:", deployment.url)
DEPLOYMENT_ID = deployment.id

# Caso contrário, se estiver em código avulso - habilitar
#DEPLOYMENT_ID = "ocid1.datasciencemodeldeployment.oc1.sa-saopaulo.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

ads.set_auth(
    auth="api_key",
    oci_config_location="/home/datascience/.oci/config",
    profile=PROFILE
)

# Recupera metadados do deployment
md = ModelDeployment.from_id(DEPLOYMENT_ID)
print("Status:", md.status)
print("Endpoint:", md.url)

# Endpoint correto (não adicionar /predict manualmente se já vier com ele)
#endpoint = "https://modeldeployment.sa-saopaulo-1.oci.customer-oci.com/ocid1.datasciencemodeldeployment.oc1.sa-saopaulo-1.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/predict"
endpoint = md.url + "/predict"

print(endpoint)

# -----------------------------
# 1) Autenticação
# -----------------------------
config = oci.config.from_file("~/.oci/config", PROFILE)
auth = Signer(
    tenancy=config["tenancy"],
    user=config["user"],
    fingerprint=config["fingerprint"],
    private_key_file_location=config["key_file"],
    pass_phrase=None,  # deixe None se a chave não tem senha
)

# -----------------------------
# 2) Payload
# -----------------------------
# 1) Colunas na ORDEM do schema
columns = [
    "gender","race","arrival_transport",
    "temperature","heartrate","resprate","o2sat","sbp","dbp",
    "n_diagnosis","los_minutes","arrival_hour","arrival_weekday"
]

# 2) Monte as linhas como dict e force a ordem virando DataFrame -> JSON records
rows_df = pd.DataFrame([
    {
        "gender":"F","race":"Caucasian","arrival_transport":"Ambulance",
        "temperature":98.6,"heartrate":88,"resprate":20,"o2sat":95,
        "sbp":110,"dbp":70,"n_diagnosis":2,"los_minutes":120.0,
        "arrival_hour":14,"arrival_weekday":"Monday"
    },
    {
        "gender":"M","race":"WHITE","arrival_transport":"WALK IN",
        "temperature":99.1,"heartrate":72,"resprate":18,"o2sat":96,
        "sbp":131,"dbp":90,"n_diagnosis":1,"los_minutes":60.0,
        "arrival_hour":23,"arrival_weekday":"Friday"
    }
])[columns]  # garante ordem

# 3) PAYLOAD: string JSON em orient="records"
payload = {"data": rows_df.to_json(orient="records")}

# -----------------------------
# 3) Chamada REST
# -----------------------------
resp = requests.post(md.url + "/predict", json=payload, auth=auth)
print(resp.status_code, resp.text)

Deployment OCID: ocid1.datasciencemodeldeployment.oc1.sa-saopaulo-1.amaaaaaafioir7iafffqtvgm2mj24zw7vnnyamcxzhwqelkdpg5n5qw4jgkq
Deployment endpoint: https://modeldeployment.sa-saopaulo-1.oci.customer-oci.com/ocid1.datasciencemodeldeployment.oc1.sa-saopaulo-1.amaaaaaafioir7iafffqtvgm2mj24zw7vnnyamcxzhwqelkdpg5n5qw4jgkq
     SUBJECT_ID     HADM_ID   STAY_ID              INTIME             OUTTIME  \
0      10014729  23300884.0  37887480 2125-03-19 12:36:00 2125-03-19 16:59:47
1      10015272  27993466.0  33473053 2137-06-12 16:54:00 2137-06-12 18:37:22
2      10016810  20973395.0  35758326 2185-06-15 23:08:00 2185-06-16 02:16:00
3      10016810         NaN  31824062 2185-07-08 11:55:00 2185-07-08 11:59:00
4      10006580         NaN  32259573 2137-09-29 21:06:00 2137-09-29 22:54:00
..          ...         ...       ...                 ...                 ...
198    10017492  27417763.0  38213541 2116-06-26 14:29:00 2116-06-26 18:26:30
199    10038999  29026789.0  34205403 2132-05-17 19:56:00 2132-05-18 01:36:00
200    10038999  27189241.0  30272878 2131-05-22 20:33:00 2131-05-22 21:50:33
201    10009049  22995465.0  31628990 2174-05-26 04:20:00 2174-05-26 09:18:00
202    10004457  28723315.0  32405286 2141-08-12 12:08:00 2141-08-12 17:20:00

    GENDER                          RACE ARRIVAL_TRANSPORT DISPOSITION  \
0        F        WHITE - OTHER EUROPEAN           WALK IN    ADMITTED
1        F                         WHITE         AMBULANCE    ADMITTED
2        F                       UNKNOWN           UNKNOWN    ADMITTED
3        F                       UNKNOWN           UNKNOWN       OTHER
4        F  HISPANIC/LATINO - SALVADORAN           WALK IN        HOME
..     ...                           ...               ...         ...
198      M    PATIENT DECLINED TO ANSWER         AMBULANCE    ADMITTED
199      M                         WHITE         AMBULANCE    ADMITTED
200      M                         WHITE           UNKNOWN    ADMITTED
201      M                         WHITE         AMBULANCE    ADMITTED
202      M                         WHITE           WALK IN    ADMITTED

     ADMITTED_FROM_ED  TEMPERATURE  HEARTRATE  RESPRATE  O2SAT    SBP   DBP  \
0                   1         99.1       90.0      26.0    NaN   86.0  61.0
1                   1         97.5      118.0      18.0   96.0  100.0  56.0
2                   1         98.8       72.0      18.0   90.0   98.0  48.0
3                   0          NaN        NaN       NaN    NaN    NaN   NaN
4                   0         98.1       89.0      18.0   96.0  131.0  90.0
..                ...          ...        ...       ...    ...    ...   ...
198                 1          NaN        NaN       NaN    NaN    NaN   NaN
199                 1         97.6      116.0      14.0   99.0  140.0  78.0
200                 1          NaN        NaN       NaN    NaN    NaN   NaN
201                 1         99.0       87.0      18.0   96.0  126.0  68.0
202                 1         97.6      103.0      16.0   98.0  138.0  72.0

     N_DIAGNOSIS  SPLIT
0              4  train
1              1  train
2              1  train
3              1  train
4              1  train
..           ...    ...
198            2  train
199            2  train
200            1  train
201            1  train
202            4  train

[203 rows x 18 columns]
WARNING:py.warnings:/home/datascience/conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages/ads/model/deployment/model_deployment.py:302: UserWarning: Parameter `properties` was deprecated in 2.8.2 from ModelDeployment constructor and will be removed in 3.0.0. Please use `spec` or the builder pattern to initialize model deployment instance. Check: https://accelerated-data-science.readthedocs.io/en/latest/user_guide/model_registration/quick_start.html
  warnings.warn(

Status: State.ACTIVE
Endpoint: https://modeldeployment.sa-saopaulo-1.oci.customer-oci.com/ocid1.datasciencemodeldeployment.oc1.sa-saopaulo-1.amaaaaaafioir7iafffqtvgm2mj24zw7vnnyamcxzhwqelkdpg5n5qw4jgkq
https://modeldeployment.sa-saopaulo-1.oci.customer-oci.com/ocid1.datasciencemodeldeployment.oc1.sa-saopaulo-1.amaaaaaafioir7iafffqtvgm2mj24zw7vnnyamcxzhwqelkdpg5n5qw4jgkq/predict
200 {"prediction":[1,1]}

In [ ]:
## Consumindo o Endpoint - Código mais sofisticado para visualização

# === Consumo do endpoint com comparação TARGET vs PRED ===
import os
import io
import json
import requests
import oci
from oci.signer import Signer
import pandas as pd
import numpy as np

# -----------------------------
# Parâmetros
# -----------------------------
PROFILE      = "DEFAULT"  # ou "LATINOAMERICA-SaoPaulo", etc
TARGET_COL   = "admitted_from_ed"  # seu alvo 0/1
#DEPLOYMENT_ID = deployment.id  # se você já tem o objeto deployment no notebook
# Caso esteja fora do notebook de deploy, comente a linha acima e defina manualmente:
DEPLOYMENT_ID = "ocid1.datasciencemodeldeployment.oc1.sa-saopaulo-1.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

# Colunas de entrada exigidas pelo modelo (na ORDEM do schema)
FEATURE_COLS = [
    "gender","race","arrival_transport",
    "temperature","heartrate","resprate","o2sat","sbp","dbp",
    "n_diagnosis","los_minutes","arrival_hour","arrival_weekday"
]

# Conexão ao ADB (wallet zip local ao notebook)
connection_parameters = {
    "user_name": "admin",
    "password": "********",
    "service_name": "oradb23ai_high",
    "wallet_location": "Wallet.zip",
}

# -----------------------------
# 0) Lê TODAS as linhas da tabela (com todas as colunas)
# -----------------------------
import ads, ads.dbmixin.db_pandas_accessor  # habilita pd.DataFrame.ads

df = pd.DataFrame.ads.read_sql(
    """
    SELECT *
    FROM ADMIN.DATASET_ED_ADMISSION
    WHERE SPLIT <= :split
    """,
    bind_variables={"split": "test"},
    connection_parameters=connection_parameters,
)

# Mostrar todas as colunas/linhas (cuidado: pode ser grande!)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
print("---- DataFrame carregado do banco ----")

# -----------------------------
# 1) Normaliza nomes e cria features derivadas se faltarem
# -----------------------------
def normalize_cols(_df: pd.DataFrame) -> pd.DataFrame:
    cols = (
        _df.columns.astype(str)
          .str.strip()
          .str.replace(r"\s+", "_", regex=True)
          .str.replace(r"[^\w]+", "_", regex=True)
          .str.replace(r"_+", "_", regex=True)
          .str.strip("_")
          .str.lower()
    )
    out = _df.copy()
    out.columns = cols
    return out

dfn = normalize_cols(df)

# converte possiveis datas
for c in ["intime","outtime"]:
    if c in dfn.columns:
        dfn[c] = pd.to_datetime(dfn[c], errors="coerce")

# cria as 3 features se possível
if {"intime","outtime"} <= set(dfn.columns):
    dfn["los_minutes"] = (dfn["outtime"] - dfn["intime"]).dt.total_seconds()/60
if "intime" in dfn.columns:
    dfn["arrival_hour"] = dfn["intime"].dt.hour
    dfn["arrival_weekday"] = dfn["intime"].dt.day_name()

# garante tipos básicos coerentes (numerics onde faz sentido)
for num_col in ["temperature","heartrate","resprate","o2sat","sbp","dbp","n_diagnosis","los_minutes","arrival_hour"]:
    if num_col in dfn.columns:
        dfn[num_col] = pd.to_numeric(dfn[num_col], errors="coerce")

# -----------------------------
# 2) Autenticação OCI e URL do deployment
# -----------------------------
from ads.model.deployment import ModelDeployment
ads.set_auth(auth="api_key", oci_config_location="~/.oci/config", profile=PROFILE)
md = ModelDeployment.from_id(DEPLOYMENT_ID)
endpoint = md.url.rstrip("/") + "/predict"
print("Status:", md.status)
print("Endpoint:", endpoint)

config = oci.config.from_file("~/.oci/config", PROFILE)
signer = Signer(
    tenancy=config["tenancy"],
    user=config["user"],
    fingerprint=config["fingerprint"],
    private_key_file_location=config["key_file"],
    pass_phrase=config.get("pass_phrase"),
)

# -----------------------------
# 3) Monta payloads em lotes e chama a API
# -----------------------------
# Verifica se todas as features existem
missing = [c for c in FEATURE_COLS if c not in dfn.columns]
if missing:
    raise ValueError(f"As seguintes colunas exigidas pelo modelo estão ausentes em dfn: {missing}")

# DataFrame apenas de features, preservando índice para recombinar depois
X_all = dfn[FEATURE_COLS].copy()

# Função que prepara payload no formato esperado: {"data": "<json records>"}
def make_payload(df_part: pd.DataFrame) -> dict:
    # Atenção: o seu deploy espera string JSON em orient="records" dentro de "data"
    return {"data": df_part.to_json(orient="records")}

# bateladas para não enviar tudo de uma vez
BATCH = 500
preds = []

for start in range(0, len(X_all), BATCH):
    part = X_all.iloc[start:start+BATCH]
    payload = make_payload(part)
    resp = requests.post(endpoint, json=payload, auth=signer, timeout=120)
    if resp.status_code != 200:
        raise RuntimeError(f"Falha no /predict (status {resp.status_code}): {resp.text}")
    out = resp.json()
    # Aceita { "prediction": [...] } ou { "data": [...] }
    if isinstance(out, dict) and "prediction" in out:
        preds.extend(out["prediction"])
    elif isinstance(out, dict) and "data" in out:
        preds.extend(out["data"])
    else:
        raise RuntimeError(f"Resposta de formato inesperado: {out}")

# -----------------------------
# 4) Junta com o DataFrame original e destaca o TARGET vs pred
# -----------------------------
result = dfn.copy()
result["prediction"] = preds[:len(result)]  # segurança caso algo retorne a mais

if TARGET_COL in result.columns:
    # normaliza tipo do alvo
    result[TARGET_COL] = pd.to_numeric(result[TARGET_COL], errors="coerce").astype("Int64")
    # pred em inteiro se veio prob/classe float
    try:
        result["prediction"] = pd.to_numeric(result["prediction"], errors="coerce")
        # se vier probabilidade, binariza em 0/1 só para comparação visual:
        if result["prediction"].between(0,1).all():
            result["prediction_class"] = (result["prediction"] >= 0.5).astype("Int64")
            result["match"] = (result["prediction_class"] == result[TARGET_COL])
        else:
            result["prediction_class"] = result["prediction"].astype("Int64")
            result["match"] = (result["prediction_class"] == result[TARGET_COL])
    except Exception:
        # se for string/categoria
        result["prediction_class"] = result["prediction"]
        result["match"] = (result["prediction_class"].astype(str) == result[TARGET_COL].astype(str))
else:
    result["match"] = pd.NA  # sem target para comparar

print("---- Resultado (todas as colunas + prediction) ----")
display(result)

# Estilo: destaca acertos/erros
def highlight_match(row):
    if pd.isna(row.get("match", pd.NA)):
        return [""] * len(row)
    return [
        "background-color: #d1fae5" if row["match"] is True and col in (TARGET_COL, "prediction", "prediction_class")
        else "background-color: #fee2e2" if row["match"] is False and col in (TARGET_COL, "prediction", "prediction_class")
        else ""
        for col in row.index
    ]

try:
    styled = result.style.apply(highlight_match, axis=1)
    display(styled)
except Exception:
    # fallback: sem estilo
    display(result)

---- DataFrame carregado do banco ----
WARNING:py.warnings:/home/datascience/conda/automlx251_p311_cpu_x86_64_v2/lib/python3.11/site-packages/ads/model/deployment/model_deployment.py:302: UserWarning: Parameter `properties` was deprecated in 2.8.2 from ModelDeployment constructor and will be removed in 3.0.0. Please use `spec` or the builder pattern to initialize model deployment instance. Check: https://accelerated-data-science.readthedocs.io/en/latest/user_guide/model_registration/quick_start.html
  warnings.warn(

Status: State.ACTIVE
Endpoint: https://modeldeployment.sa-saopaulo-1.oci.customer-oci.com/ocid1.datasciencemodeldeployment.oc1.sa-saopaulo-1.amaaaaaafioir7iafffqtvgm2mj24zw7vnnyamcxzhwqelkdpg5n5qw4jgkq/predict
---- Resultado (todas as colunas + prediction) ----

,subject_id,hadm_id,stay_id,intime,outtime,gender,race,arrival_transport,disposition,admitted_from_ed,temperature,heartrate,resprate,o2sat,sbp,dbp,n_diagnosis,split,los_minutes,arrival_hour,arrival_weekday,prediction,prediction_class,match
0,10001217,24597018.0,39866888,2157-11-18 17:38:00,2157-11-19 01:24:00,F,WHITE,WALK IN,ADMITTED,1,99.0,81.0,16.0,97.0,160.0,102.0,2,test,466.000000,17,Friday,1,1,True
1,10001217,NaN,39300221,2157-11-29 19:28:00,2157-11-29 21:22:00,F,WHITE,WALK IN,HOME,0,98.0,75.0,20.0,98.0,132.0,95.0,1,test,114.000000,19,Tuesday,1,1,False
2,10014078,25809882.0,38676365,2166-08-21 21:39:00,2166-08-22 00:36:00,F,UNABLE TO OBTAIN,AMBULANCE,ADMITTED,1,NaN,NaN,NaN,NaN,NaN,NaN,1,test,177.000000,21,Thursday,1,1,True
3,10037928,23721604.0,32259566,2179-03-27 14:15:00,2179-03-27 19:48:00,F,HISPANIC/LATINO - CUBAN,AMBULANCE,ADMITTED,1,99.8,97.0,32.0,88.0,176.0,86.0,1,test,333.000000,14,Saturday,1,1,True
4,10037928,NaN,32891808,2178-01-24 21:23:00,2178-01-24 23:59:00,F,HISPANIC/LATINO - CUBAN,WALK IN,HOME,0,97.0,81.0,18.0,99.0,161.0,55.0,4,test,156.000000,21,Saturday,1,1,False
5,10037928,NaN,34992024,2183-11-28 17:19:00,2183-11-28 23:57:00,F,HISPANIC/LATINO - CUBAN,AMBULANCE,HOME,0,36.5,95.0,18.0,98.0,150.0,56.0,6,test,398.000000,17,Friday,0,0,True
6,10037928,29802992.0,37953392,2179-07-24 18:21:00,2179-07-25 01:17:00,F,HISPANIC/LATINO - CUBAN,AMBULANCE,ADMITTED,1,98.3,76.0,16.0,98.0,144.0,56.0,6,test,416.000000,18,Saturday,1,1,True
7,10037928,22228639.0,35156583,2183-08-03 19:27:00,2183-08-04 16:07:00,F,HISPANIC/LATINO - CUBAN,AMBULANCE,HOME,1,97.8,75.0,16.0,95.0,159.0,60.0,3,test,1240.000000,19,Sunday,1,1,True
8,10037928,22490490.0,38207210,2177-07-14 14:52:00,2177-07-14 20:38:00,F,HISPANIC/LATINO - CUBAN,AMBULANCE,ADMITTED,1,98.2,72.0,16.0,96.0,126.0,43.0,2,test,346.000000,14,Monday,1,1,True
9,10037928,24885579.0,37483564,2182-04-28 17:25:00,2182-04-29 07:49:00,F,HISPANIC/LATINO - CUBAN,WALK IN,ADMITTED,1,98.2,105.0,24.0,96.0,177.0,69.0,1,test,864.000000,17,Sunday,1,1,True
10,10037928,24656677.0,32443787,2178-12-21 03:17:00,2178-12-21 05:30:41,F,HISPANIC/LATINO - CUBAN,AMBULANCE,ADMITTED,1,98.1,130.0,15.0,95.0,179.0,69.0,1,test,133.683333,3,Monday,1,1,True
11,10037928,22326517.0,39740242,2177-12-21 16:49:00,2177-12-21 22:26:00,F,HISPANIC/LATINO - CUBAN,WALK IN,ADMITTED,1,98.7,108.0,22.0,98.0,151.0,55.0,3,test,337.000000,16,Sunday,1,1,True
12,10037928,24225421.0,34478228,2178-09-28 20:29:00,2178-09-29 00:43:00,F,HISPANIC/LATINO - CUBAN,WALK IN,ADMITTED,1,97.6,96.0,16.0,94.0,121.0,65.0,3,test,254.000000,20,Monday,1,1,True
13,10037928,20192635.0,37036523,2177-09-04 06:29:00,2177-09-04 12:06:40,F,HISPANIC/LATINO - CUBAN,AMBULANCE,ADMITTED,1,NaN,NaN,NaN,NaN,NaN,NaN,3,test,337.666667,6,Thursday,1,1,True
14,10019003,27525946.0,38260469,2153-04-12 13:03:00,2153-04-12 21:40:00,F,WHITE,WALK IN,ADMITTED,1,99.1,96.0,17.0,96.0,114.0,66.0,1,test,517.000000,13,Thursday,1,1,True
15,10019003,29279905.0,31254712,2153-03-27 21:28:00,2153-03-28 02:21:00,F,WHITE,AMBULANCE,ADMITTED,1,98.4,96.0,15.0,97.0,98.0,56.0,4,test,293.000000,21,Tuesday,1,1,True
16,10019003,26529390.0,38020791,2155-05-17 21:03:00,2155-05-18 00:03:15,F,WHITE,WALK IN,ADMITTED,1,98.1,97.0,16.0,93.0,117.0,60.0,1,test,180.250000,21,Saturday,1,1,True
17,10019003,26703331.0,35568186,2155-06-10 20:37:00,2155-06-10 23:10:36,F,WHITE,AMBULANCE,ADMITTED,1,97.8,92.0,26.0,95.0,116.0,57.0,3,test,153.600000,20,Tuesday,1,1,True
18,10019003,21457723.0,36686656,2155-07-10 12:46:00,2155-07-10 17:48:57,F,WHITE,AMBULANCE,ADMITTED,1,98.6,98.0,16.0,97.0,105.0,43.0,2,test,302.950000,12,Thursday,1,1,True
19,10003400,22390287.0,34922474,2137-02-07 13:06:00,2137-02-07 21:44:00,F,BLACK/AFRICAN AMERICAN,AMBULANCE,ADMITTED,1,98.8,124.0,16.0,98.0,136.0,82.0,3,test,518.000000,13,Thursday,1,1,True
20,10003400,26467376.0,33678912,2136-12-09 13:16:00,2136-12-09 14:45:10,F,BLACK/AFRICAN AMERICAN,AMBULANCE,ADMITTED,1,98.3,157.0,18.0,100.0,115.0,81.0,2,test,89.166667,13,Sunday,1,1,True
21,10003400,27296885.0,36976997,2136-12-31 13:41:00,2137-01-01 00:35:00,F,BLACK/AFRICAN AMERICAN,AMBULANCE,ADMITTED,1,97.7,91.0,16.0,100.0,111.0,68.0,2,test,654.000000,13,Monday,1,1,True
22,10003400,26090619.0,33347721,2134-06-05 21:42:00,2134-06-06 03:44:00,F,BLACK/AFRICAN AMERICAN,OTHER,ADMITTED,1,97.3,43.0,16.0,99.0,140.0,100.0,4,test,362.000000,21,Saturday,1,1,True
23,10003400,29483621.0,34948767,2136-11-04 16:08:00,2136-11-04 22:12:00,F,BLACK/AFRICAN AMERICAN,WALK IN,ADMITTED,1,99.9,86.0,18.0,100.0,142.0,92.0,2,test,364.000000,16,Sunday,0,0,False
24,10002930,28697806.0,32272346,2200-06-04 16:38:00,2200-06-05 10:26:00,F,BLACK/AFRICAN AMERICAN,AMBULANCE,HOME,1,97.3,89.0,16.0,100.0,106.0,61.0,3,test,1068.000000,16,Wednesday,1,1,True
25,10002930,25696644.0,31579293,2196-04-14 05:55:00,2196-04-14 13:40:00,F,BLACK/AFRICAN AMERICAN,UNKNOWN,ADMITTED,1,95.6,89.0,16.0,100.0,106.0,65.0,3,test,465.000000,5,Thursday,1,1,True
26,10002930,20282368.0,39266792,2201-03-23 12:04:00,2201-03-26 14:24:00,F,BLACK/AFRICAN AMERICAN,AMBULANCE,TRANSFER,1,98.1,76.0,18.0,100.0,181.0,94.0,3,test,4460.000000,12,Monday,1,1,True
27,10002930,25922998.0,30193781,2198-04-17 11:42:00,2198-04-17 21:24:00,F,BLACK/AFRICAN AMERICAN,WALK IN,ADMITTED,1,98.2,88.0,16.0,100.0,150.0,98.0,3,test,582.000000,11,Tuesday,0,0,False
28,10002930,28477649.0,38615683,2197-04-07 03:20:00,2197-04-07 06:56:40,F,BLACK/AFRICAN AMERICAN,AMBULANCE,ADMITTED,1,97.5,108.0,16.0,100.0,154.0,92.0,1,test,216.666667,3,Friday,1,1,True
29,10002930,25282382.0,35540249,2197-04-16 22:57:00,2197-04-17 09:48:00,F,BLACK/AFRICAN AMERICAN,WALK IN,HOME,1,98.5,110.0,18.0,100.0,123.0,67.0,3,test,651.000000,22,Sunday,1,1,True
30,10002930,23720373.0,35114287,2199-02-17 14:32:00,2199-02-19 13:38:00,F,BLACK/AFRICAN AMERICAN,AMBULANCE,TRANSFER,1,98.9,102.0,20.0,100.0,180.0,85.0,4,test,2826.000000,14,Sunday,1,1,True
31,10002930,20846853.0,39910144,2201-02-12 15:11:00,2201-02-13 11:11:00,F,BLACK/AFRICAN AMERICAN,AMBULANCE,HOME,1,97.7,103.0,18.0,97.0,137.0,87.0,3,test,1200.000000,15,Thursday,1,1,True
32,10021938,NaN,38449411,2181-09-02 19:21:00,2181-09-03 01:49:00,M,WHITE,AMBULANCE,HOME,0,NaN,NaN,NaN,NaN,NaN,NaN,1,test,388.000000,19,Sunday,1,1,False
33,10021938,23112364.0,38890884,2181-10-12 20:17:00,2181-10-13 02:52:00,M,WHITE,AMBULANCE,ADMITTED,1,99.8,110.0,18.0,93.0,178.0,85.0,1,test,395.000000,20,Friday,1,1,True
34,10021938,27154822.0,32204198,2181-10-25 09:23:00,2181-10-25 11:35:00,M,WHITE,AMBULANCE,ADMITTED,1,98.4,89.0,18.0,97.0,217.0,116.0,1,test,132.000000,9,Thursday,1,1,True
35,10005866,27167814.0,30804580,2148-03-10 04:46:00,2148-03-10 16:18:48,M,PORTUGUESE,AMBULANCE,ADMITTED,1,97.4,66.0,18.0,99.0,111.0,68.0,1,test,692.800000,4,Sunday,1,1,True
36,10005866,26134779.0,31806264,2149-09-12 15:31:00,2149-09-13 09:02:00,M,PORTUGUESE,WALK IN,ADMITTED,1,98.2,84.0,18.0,100.0,175.0,80.0,1,test,1051.000000,15,Friday,1,1,True
37,10005866,22589518.0,32537287,2149-02-11 08:52:00,2149-02-11 23:09:00,M,PORTUGUESE,WALK IN,ADMITTED,1,98.0,82.0,22.0,100.0,157.0,82.0,1,test,857.000000,8,Tuesday,1,1,True
38,10005866,NaN,31023359,2149-09-28 01:53:00,2149-09-28 16:26:00,M,PORTUGUESE,WALK IN,HOME,0,97.2,88.0,18.0,100.0,163.0,89.0,4,test,873.000000,1,Sunday,1,1,False
39,10005866,21636229.0,30225689,2149-09-20 05:50:00,2149-09-20 15:53:00,M,PORTUGUESE,WALK IN,ADMITTED,1,97.6,72.0,16.0,100.0,163.0,81.0,1,test,603.000000,5,Saturday,1,1,True
40,10005866,NaN,32281632,2148-06-13 08:36:00,2148-06-13 17:30:00,M,PORTUGUESE,AMBULANCE,TRANSFER,0,97.9,63.0,18.0,99.0,149.0,72.0,1,test,534.000000,8,Thursday,1,1,False
41,10005866,23514107.0,35681380,2149-06-20 10:20:00,2149-06-20 20:59:00,M,PORTUGUESE,WALK IN,ADMITTED,1,98.0,76.0,18.0,99.0,147.0,92.0,1,test,639.000000,10,Friday,1,1,True
42,10005866,26158160.0,34558830,2146-06-05 22:26:00,2146-06-06 01:45:00,M,PORTUGUESE,AMBULANCE,ADMITTED,1,NaN,NaN,NaN,NaN,NaN,NaN,1,test,199.000000,22,Sunday,1,1,True
43,10005866,20364112.0,31121963,2149-10-01 02:07:00,2149-10-01 18:56:59,M,PORTUGUESE,AMBULANCE,ADMITTED,1,98.8,106.0,20.0,100.0,163.0,103.0,2,test,1009.983333,2,Wednesday,1,1,True
44,10026406,NaN,39571461,2129-11-25 19:02:00,2129-11-26 00:46:00,M,WHITE,WALK IN,HOME,0,98.7,118.0,22.0,99.0,131.0,89.0,1,test,344.000000,19,Friday,1,1,False
45,10026406,25260176.0,37202404,2129-01-02 23:41:00,2129-01-03 18:33:00,M,WHITE,AMBULANCE,ADMITTED,1,98.0,105.0,20.0,98.0,153.0,77.0,4,test,1132.000000,23,Sunday,1,1,True
46,10026406,25166559.0,38237602,2133-03-01 16:42:00,2133-03-04 17:05:00,M,WHITE,WALK IN,HOME,1,97.0,98.0,20.0,99.0,133.0,110.0,4,test,4343.000000,16,Sunday,1,1,True
47,10025463,24470193.0,35470228,2137-10-08 18:16:00,2137-10-08 21:20:50,M,WHITE,AMBULANCE,OTHER,1,NaN,NaN,NaN,NaN,NaN,NaN,1,test,184.833333,18,Tuesday,1,1,True